# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\firstPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def get(self):
        print('work owrk work')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signin = QtWidgets.QToolButton(self.centralwidget)
        self.signin.setGeometry(QtCore.QRect(190, 230, 441, 111))
        self.signin.setObjectName("signin")
        self.signUp = QtWidgets.QPushButton(self.centralwidget)
        self.signUp.setGeometry(QtCore.QRect(190, 60, 441, 121))
        self.signUp.setMouseTracking(False)
        self.signUp.setCheckable(False)
        self.signUp.setObjectName("signUp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.signUp.clicked.connect(self.get)
        self.signin.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signin.setText(_translate("MainWindow", "I already have an account."))
        self.signUp.setText(_translate("MainWindow", "I don’t have any account and I want to register."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
