# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\forgetPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IDNum = QtWidgets.QLineEdit(self.centralwidget)
        self.IDNum.setGeometry(QtCore.QRect(275, 140, 250, 60))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.IDNum.setFont(font)
        self.IDNum.setAutoFillBackground(True)
        self.IDNum.setText("")
        self.IDNum.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.IDNum.setAlignment(QtCore.Qt.AlignCenter)
        self.IDNum.setObjectName("IDNum")
        self.Useraame = QtWidgets.QLineEdit(self.centralwidget)
        self.Useraame.setGeometry(QtCore.QRect(275, 30, 250, 61))
        self.Useraame.setInputMask("")
        self.Useraame.setText("")
        self.Useraame.setAlignment(QtCore.Qt.AlignCenter)
        self.Useraame.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.Useraame.setObjectName("Useraame")
        self.showPass = QtWidgets.QPushButton(self.centralwidget)
        self.showPass.setGeometry(QtCore.QRect(300, 230, 200, 51))
        self.showPass.setDefault(False)
        self.showPass.setObjectName("showPass")
        self.logger = QtWidgets.QTextBrowser(self.centralwidget)
        self.logger.setGeometry(QtCore.QRect(40, 340, 700, 192))
        self.logger.setFrameShape(QtWidgets.QFrame.Box)
        self.logger.setObjectName("logger")
        self.ID_label = QtWidgets.QLabel(self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(120, 150, 131, 41))
        self.ID_label.setObjectName("ID_label")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(120, 40, 121, 41))
        self.user_label.setObjectName("user_label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(350, 285, 100, 51))
        self.back.setDefault(False)
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.showPass.clicked.connect(MainWindow.deleteLater)
        self.back.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IDNum.setPlaceholderText(_translate("MainWindow", "ID NUMBER"))
        self.Useraame.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.showPass.setText(_translate("MainWindow", "Show Password"))
        self.ID_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ID Number :</span></p></body></html>"))
        self.user_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Username :</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
