# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginPannel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(275, 140, 250, 60))
        self.Password.setAutoFillBackground(True)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Useraame = QtWidgets.QLineEdit(self.centralwidget)
        self.Useraame.setGeometry(QtCore.QRect(275, 30, 250, 61))
        self.Useraame.setInputMask("")
        self.Useraame.setText("")
        self.Useraame.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.Useraame.setObjectName("Useraame")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(270, 230, 100, 51))
        self.login.setDefault(False)
        self.login.setObjectName("login")
        self.logger = QtWidgets.QTextBrowser(self.centralwidget)
        self.logger.setGeometry(QtCore.QRect(40, 340, 700, 192))
        self.logger.setFrameShape(QtWidgets.QFrame.Box)
        self.logger.setObjectName("logger")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(120, 150, 131, 41))
        self.password_label.setObjectName("password_label")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(120, 40, 121, 41))
        self.user_label.setObjectName("user_label")
        self.forget = QtWidgets.QPushButton(self.centralwidget)
        self.forget.setGeometry(QtCore.QRect(560, 150, 180, 40))
        self.forget.setDefault(False)
        self.forget.setObjectName("forget")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(370, 230, 100, 51))
        self.back.setDefault(False)
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.login.clicked.connect(MainWindow.deleteLater)
        self.back.clicked.connect(MainWindow.deleteLater)
        self.forget.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.Useraame.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.login.setText(_translate("MainWindow", "login"))
        self.password_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password :</span></p></body></html>"))
        self.user_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Username :</span></p></body></html>"))
        self.forget.setText(_translate("MainWindow", "Forget Password"))
        self.back.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
