# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QuestionPan.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 110, 700, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.op1 = QtWidgets.QPushButton(self.centralwidget)
        self.op1.setGeometry(QtCore.QRect(80, 270, 120, 61))
        self.op1.setObjectName("op1")
        self.op2 = QtWidgets.QPushButton(self.centralwidget)
        self.op2.setGeometry(QtCore.QRect(250, 270, 120, 61))
        self.op2.setObjectName("op2")
        self.po3 = QtWidgets.QPushButton(self.centralwidget)
        self.po3.setGeometry(QtCore.QRect(420, 270, 120, 61))
        self.po3.setObjectName("po3")
        self.op4 = QtWidgets.QPushButton(self.centralwidget)
        self.op4.setGeometry(QtCore.QRect(590, 270, 120, 61))
        self.op4.setObjectName("op4")
        self.Qustion_label = QtWidgets.QLabel(self.centralwidget)
        self.Qustion_label.setGeometry(QtCore.QRect(50, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Qustion_label.setFont(font)
        self.Qustion_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Qustion_label.setObjectName("Qustion_label")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setGeometry(QtCore.QRect(80, 440, 300, 51))
        self.previous.setObjectName("previous")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(410, 440, 300, 51))
        self.next.setObjectName("next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.op1.clicked.connect(MainWindow.deleteLater)
        self.op2.clicked.connect(MainWindow.deleteLater)
        self.op4.clicked.connect(MainWindow.deleteLater)
        self.po3.clicked.connect(MainWindow.deleteLater)
        self.previous.clicked.connect(MainWindow.deleteLater)
        self.next.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.op1.setText(_translate("MainWindow", "PushButton"))
        self.op2.setText(_translate("MainWindow", "PushButton"))
        self.po3.setText(_translate("MainWindow", "PushButton"))
        self.op4.setText(_translate("MainWindow", "PushButton"))
        self.Qustion_label.setText(_translate("MainWindow", "Qustion"))
        self.previous.setText(_translate("MainWindow", "Previous Question"))
        self.next.setText(_translate("MainWindow", "Next Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
