# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\quizlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUiQuizlist(self):
        MainWindow = self.MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(400, 200, 320, 61))
        self.start.setObjectName("start")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(60, 200, 320, 61))
        self.back.setObjectName("back")
        self.quizlist = QtWidgets.QComboBox(self.centralwidget)
        self.quizlist.setGeometry(QtCore.QRect(190, 120, 381, 31))
        self.quizlist.setObjectName("quizlist")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 320, 681, 192))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        Quiz_list = os.listdir(path='Quizes')

        for i in range(len(Quiz_list)):
            self.quizlist.addItem(Quiz_list[i])

        
        def temp_choose():
            self.chosen_file = self.quizlist.currentIndex()
            print(self.chosen_file)


        self.retranslateUiQiuzlist(MainWindow)
        self.back.clicked.connect(MainWindow.deleteLater)
        self.start.clicked.connect(MainWindow.deleteLater)
        self.quizlist.activated['QString'].connect(temp_chosen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUiQiuzlist(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Start Quiz"))
        self.back.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
