# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resultPan.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Questions_result = QtWidgets.QTableWidget(self.centralwidget)
        self.Questions_result.setGeometry(QtCore.QRect(20, 10, 861, 461))
        self.Questions_result.setObjectName("Questions_result")
        self.Questions_result.setColumnCount(0)
        self.Questions_result.setRowCount(0)
        self.signout = QtWidgets.QPushButton(self.centralwidget)
        self.signout.setGeometry(QtCore.QRect(470, 650, 411, 61))
        self.signout.setObjectName("signout")
        self.NewQuiz = QtWidgets.QPushButton(self.centralwidget)
        self.NewQuiz.setGeometry(QtCore.QRect(20, 650, 411, 61))
        self.NewQuiz.setObjectName("NewQuiz")
        self.total_results = QtWidgets.QTableWidget(self.centralwidget)
        self.total_results.setGeometry(QtCore.QRect(20, 490, 861, 131))
        self.total_results.setObjectName("total_results")
        self.total_results.setColumnCount(0)
        self.total_results.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.signout.clicked.connect(MainWindow.deleteLater)
        self.NewQuiz.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signout.setText(_translate("MainWindow", "Sign Out"))
        self.NewQuiz.setText(_translate("MainWindow", "Start New Quiz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
