# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(275, 140, 250, 61))
        self.Password.setAutoFillBackground(True)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Useraame = QtWidgets.QLineEdit(self.centralwidget)
        self.Useraame.setGeometry(QtCore.QRect(275, 30, 250, 61))
        self.Useraame.setInputMask("")
        self.Useraame.setText("")
        self.Useraame.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.Useraame.setObjectName("Useraame")
        self.SignUp = QtWidgets.QPushButton(self.centralwidget)
        self.SignUp.setGeometry(QtCore.QRect(330, 380, 100, 51))
        self.SignUp.setDefault(False)
        self.SignUp.setObjectName("SignUp")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(120, 150, 131, 41))
        self.password_label.setObjectName("password_label")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(120, 40, 121, 41))
        self.user_label.setObjectName("user_label")
        self.password_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.password_label_2.setGeometry(QtCore.QRect(110, 270, 131, 41))
        self.password_label_2.setObjectName("password_label_2")
        self.ID_Number = QtWidgets.QLineEdit(self.centralwidget)
        self.ID_Number.setGeometry(QtCore.QRect(275, 260, 250, 61))
        self.ID_Number.setAutoFillBackground(True)
        self.ID_Number.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ID_Number.setObjectName("ID_Number")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(440, 380, 100, 51))
        self.back.setDefault(False)
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SignUp.clicked.connect(MainWindow.deleteLater)
        self.back.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.Useraame.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.SignUp.setText(_translate("MainWindow", "SignUp"))
        self.password_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password :</span></p></body></html>"))
        self.user_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Username :</span></p></body></html>"))
        self.password_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ID Number :</span></p></body></html>"))
        self.ID_Number.setPlaceholderText(_translate("MainWindow", "ID NUMBER"))
        self.back.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
